---

definitions:
  installscript: &baseInstallDeps
    export DEBIAN_FRONTEND='noninteractive' ;
    export COMPOSER_ALLOW_SUPERUSER=1 ;
    IPADDRESS=$(grep "$HOSTNAME$" /etc/hosts | grep -Po '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}') ; export IPADDRESS ;
    apt-get -qq update &&
    mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7 &&
    apt-get -qq install default-jre-headless postgresql-client mariadb-client &&
    curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash &&
    . ~/.bashrc &&
    nvm install -b --no-progress v14.15.0 &&
    curl -sS https://getcomposer.org/installer | php -- --install-dir='/usr/local/bin' --filename='composer' &&
    touch /usr/local/bin/phpenv && chmod +x /usr/local/bin/phpenv &&
    mkdir -pv /tmp/plugin ; cp -ru "${BITBUCKET_CLONE_DIR}"/* /tmp/plugin ; rm -rf "${BITBUCKET_CLONE_DIR:?}"/* ;
    mkdir -pv "${BITBUCKET_CLONE_DIR}/plugin" && cp -ru /tmp/plugin/* "${BITBUCKET_CLONE_DIR}"/plugin ;
    composer create-project -n --no-dev --no-progress --no-ansi --prefer-dist moodlehq/moodle-plugin-ci ci ^3 &&
    { [ "${MOODLE_START_BEHAT_SERVERS}" = '' ] && export MOODLE_START_BEHAT_SERVERS='NO' ; } ;
    { [ "${MOODLE_BEHAT_WWWROOT}" = '' ] && export MOODLE_BEHAT_WWWROOT="http://$IPADDRESS:8000" ; } ;
    { [ "${MOODLE_BEHAT_WDHOST}" = '' ] && export MOODLE_BEHAT_WDHOST="http://$IPADDRESS:4444/wd/hub" ; } ;
    { [ "${MOODLE_REPO}" = '' ] && export MOODLE_REPO='https://bitbucket.org/moodle/moodle.git' ; } ;
    { [ "${MOODLE_BRANCH}" = '' ] && export MOODLE_BRANCH='MOODLE_311_STABLE' ; } ;
    { [ "${DB}" = '' ] && export DB='mariadb' ; } ;
    { [ "${DB_USER}" = '' ] && export DB_USER='root' ; } ;
    { [ "${DB_PWD}" = '' ] && export DB_PWD='test' ; } ;
    export TRAVIS_BUILD_DIR="$BITBUCKET_CLONE_DIR/plugin" ;
    export PATH="$BITBUCKET_CLONE_DIR/ci/bin:$BITBUCKET_CLONE_DIR/ci/vendor/bin:$PATH" ;
  instscript: &baseInst
    moodle-plugin-ci install --no-ansi -n --db-type="$DB" --db-user="$DB_USER" --db-pass="$DB_PWD"
    --branch="$MOODLE_BRANCH" --db-host="127.0.0.1"
  behatscript: &baseBehat
    docker run -d -p 4444:4444 --shm-size=1g -v "$BITBUCKET_CLONE_DIR/moodle:$BITBUCKET_CLONE_DIR/moodle"
    "selenium/standalone-firefox:3" &&
    { php -S 0.0.0.0:8000 -t "$BITBUCKET_CLONE_DIR/moodle" > /dev/null 2>&1 & } ; sleep 10 ;
  steps:
    - step: &base
        image: moodlehq/moodle-php-apache:7.3
        name: "Moodle, PHP 7.3 and MariaDB"
        caches:
          - composer
          - npm
          - docker
        script:
          - *baseInstallDeps
          - *baseInst
          - *baseBehat
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
          - moodle-plugin-ci behat
        services:
          - mariadb
          - docker
  services:
    mariadb:
      image: mariadb:10.5
      variables:
        MARIADB_ROOT_PASSWORD: test
    mysql:
      image: mysql:5.7
      variables:
        MYSQL_ROOT_PASSWORD: test
    postgres:
      image: postgres:10
      variables:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: test
  caches:
    npm: $HOME/.npm

pipelines:
  default:
    - step: *base
    - step:
        <<: *base
        image: moodlehq/moodle-php-apache:7.4
        name: "Moodle, PHP 7.4 and MySQL 5.7"
        script:
          - export DB='mysqli'
          - *baseInstallDeps
          - *baseInst
          - *baseBehat
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
          - moodle-plugin-ci behat
        services:
          - mysql
          - docker
    - step:
        <<: *base
        image: moodlehq/moodle-php-apache:8.0
        name: "Moodle, PHP 8.0 and PostgreSQL 10"
        script:
          - export DB='pgsql'
          - *baseInstallDeps
          - *baseInst
          - *baseBehat
          - moodle-plugin-ci phplint
          - moodle-plugin-ci phpcpd
          - moodle-plugin-ci phpmd
          - moodle-plugin-ci codechecker
          - moodle-plugin-ci validate
          - moodle-plugin-ci savepoints
          - moodle-plugin-ci mustache
          - moodle-plugin-ci grunt
          - moodle-plugin-ci phpdoc
          - moodle-plugin-ci phpunit
          - moodle-plugin-ci behat
        services:
          - postgres
          - docker
